---
version: '3.2'

services:
  terraform:
    image: hashicorp/terraform:0.14.6
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_DEFAULT_REGION
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_SHARED_CREDENTIALS_FILE=/app/.aws/credentials
    working_dir: /app/infra
    volumes:
      - ./infra:/app/infra/:rw

  terraform-compliance:
    image: eerkunt/terraform-compliance:1.3.13
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_DEFAULT_REGION
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_SHARED_CREDENTIALS_FILE=/app/.aws/credentials
    working_dir: /app/infra
    volumes:
      - ./infra:/app/infra/:rw

  python:
    image: python:latest
    working_dir: /app
    volumes:
      - .:/app/:rw
